{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP 响应吞吐量 (按方法/路由/状态码)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"sum\"), 1s) \nFROM \"vertx_http_server_response_bytes\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"method\", \"route\", \"code\" \nfill(null)"
    }
   ]
  },
  {
   "title": "SQL 处理时间 (平均值)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"sum\") / mean(\"count\") \nFROM \"vertx_sql_processing_time_seconds\" \nWHERE $timeFilter AND \"count\" > 0 \nGROUP BY time($__interval) \nfill(null)"
    }
   ]
  },
  {
   "title": "HTTP 请求速率 (按状态码/方法/路由)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 1s) FROM \"vertx_http_server_requests_total\" WHERE $timeFilter GROUP BY time($__interval), \"code\", \"method\", \"route\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " HTTP 平均响应时间 (按方法/路由/状态码)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"sum\") / mean(\"count\") \nFROM \"vertx_http_server_response_time_seconds\" \nWHERE $timeFilter AND \"count\" > 0 \nGROUP BY time($__interval), \"method\", \"route\", \"code\" \nfill(null)"
    }
   ]
  },
  {
   "title": "HTTP 服务器响应字节数总和",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vertx_http_server_response_bytes",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "活跃 HTTP 连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "      \nSELECT mean(\"gauge\") \nFROM \"vertx_http_server_active_connections\" \nWHERE $timeFilter \nGROUP BY time($__interval) \nfill(previous) -- 或者 fill(null)\n\n    "
    }
   ]
  },
  {
   "title": "活跃 HTTP 请求数 (按方法)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") \nFROM \"vertx_http_server_active_requests\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"method\" \nfill(previous)"
    }
   ]
  },
  {
   "title": "连接池状态 (按类型)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") \nFROM \"vertx_pool_in_use\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"pool_type\" \nfill(previous)"
    }
   ]
  }
 ]
}