      
# .github/workflows/backend-build.yml
name: Backend Build Pipeline (No Tests)

# 控制工作流何时运行
on:
  push:
    branches: [ "main" ] # 在推送到 main 分支时运行
    paths:
      - 'backend-app/**' # 仅当 backend-app 目录下的文件发生更改时运行
      - '.github/workflows/backend-build.yml' # 或者工作流文件本身发生更改时运行
  pull_request:
    branches: [ "main" ] # 在针对 main 分支的拉取请求时运行
    paths:
      - 'backend-app/**'
      - '.github/workflows/backend-build.yml'

jobs:
  build-and-package:
    name: Build Backend JAR and Docker Image
    runs-on: ubuntu-latest # 使用 GitHub 提供的最新 Ubuntu 运行器

    steps:
      # 步骤 1：签出仓库代码
      - name: 签出代码 (Checkout code)
        uses: actions/checkout@v4

      # 步骤 2：设置 JDK 17
      - name: 设置 JDK 17 (Set up JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # 仍然缓存 Maven 依赖，加快构建

      # 步骤 3：使用 Maven 打包 (跳过测试)
      # package 阶段仍然会编译代码
      - name: 使用 Maven 打包 (跳过测试) (Package with Maven, skip tests)
        # 在 backend-app 目录内运行 Maven
        # 使用 -DskipTests=true 来跳过测试执行
        run: mvn -B package -DskipTests=true --file backend-app/pom.xml

      # 步骤 4：设置 Docker Buildx
      - name: 设置 Docker Buildx (Set up Docker Buildx)
        uses: docker/setup-buildx-action@v3

      # 步骤 5：构建 Docker 镜像 (不推送)
      - name: 构建 Docker 镜像 (Build Docker image)
        uses: docker/build-push-action@v5
        with:
          context: ./backend-app # Dockerfile 和构建上下文所在的目录
          dockerfile: ./backend-app/Dockerfile # Dockerfile 的明确路径
          push: false # 只构建，不推送
          tags: ghcr.io/mxwj/librarymanagement-backend:latest # 示例标签，请替换为你自己的
          # 或者 Docker Hub: your-dockerhub-username/librarymanagement-backend:latest

      # 步骤 6：（可选）上传 Fat JAR 作为构建产物
      - name: 上传 Fat JAR 构建产物 (Upload Fat JAR artifact)
        uses: actions/upload-artifact@v4
        with:
          name: librarymanagement-fat-jar # 构建产物 zip 文件的名称
          path: backend-app/target/librarymanagement-*-fat.jar # fat jar 的路径
          retention-days: 7 # 保留天数

    
